{% set version = '0.5.1' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-viridis
  version: {{ version|replace("-", "_") }}

source:
  fn: viridis_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/viridis_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/viridis/viridis_{{ version }}.tar.gz
  sha256: ddf267515838c6eb092938133035cee62ab6a78760413bfc28b8256165701918

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 1001

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]

  host:
    - r-base
    - r-ggplot2 >=1.0.1
    - r-gridextra
    - r-viridislite >=0.3.0

  run:
    - r-base
    - r-ggplot2 >=1.0.1
    - r-gridextra
    - r-viridislite >=0.3.0

test:
  commands:
    - $R -e "library('viridis')"           # [not win]
    - "\"%R%\" -e \"library('viridis')\""  # [win]

about:
  home: https://github.com/sjmgarnier/viridis
  license: MIT
  summary: |
    Port of the new matplotlib color maps ('viridis' - the default -, 'magma', 'plasma'
    and 'inferno') to R. matplotlib is a popular plotting
    library for python. These color maps are designed in such a way that they will
    analytically be perfectly perceptually-uniform, both in regular form and also when
    converted to black-and-white. They are also designed to be perceived by readers
    with the most common form of color blindness.
  license_family: MIT
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'  # [unix]
  license_file: '{{ environ["PREFIX"] }}\R\share\licenses\MIT'  # [win]

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
    - roryk
