appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: QYKPN6Dx8O6j0Bc50Dvlc1zY+6+f/GtDyE0rkLZv8QwhEJk23L9dtkalRAjJYu22Y8tSZf+rbOniuI98cZgKLLjrv1Btye5qRAZYonB7Qeqc5Wevp5OI2zaZv193IATcoj1fowptMcymXkqmIVugAqod8AS2TCfR3YeBHa2d8Sv4pK724h1pAkGycWAOzfBj5RBlDuhm/6PbXDKaGb/FyuvETDHMLKUc/jHV405P4oxOIDhUbP/yV0PSDHEbfBYfyGg+3BszItpkW56dwfQJo43S4JtoUTddrYA1jgCIZJHUe/lA+uBc2h5D80KT3SWGjDIeBnpTGKkB3GkbunJGQyQf9t7qWicYVoNnHL3riPUpBaHK8Gp6BP8BxUC/Kff4jYdFHbAsR1RjDVxhNepWGUv1Ap4fnUtmG3b+4c+IHSnhFRfPL5P3+c8ra3NEHqfC3g3gQ0Jxqhdk4KhDb9KFkzPFqPS5Hc3wXTMMqLVBMyrE6Hif+TrcVguFeyoZG7yEjFgcz1uyGRrPxHMF9gsDML6tXhl0gIuBMVyXhDKIseory0FSvXNMn1JSTJ/ajSUmkfvQh6Gb+q+BJF9WPL2vtB1xS7i7Uhkew7lNLprrB3oy5/Lw0yxf2C64/flvl8KTm3uqiBFX4ThFN1pcOWT0s+FUXY5XOVCtkRMvI+tgCqU=}
bot:
  automerge: true
